services:
  simple:
    image: mongo
    ports:
      - 27019:27017

  with-replica-set:
    image: mongo
    ports:
      - 27017:27017
    command: mongod --replSet rs0
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js

  imaged:
    image: vosarat/mongo-rs0:latest
    build: .
    ports:
      - 27018:27017