name: Persic.Files NuGet
on:
  push:
    paths:
      - 'files/lib/**'
      - '.github/workflows/files-nuget.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: files/lib/Persic.Files
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}